# build environment
FROM node:13.12.0-alpine
ENV REACT_APP_MODE=staging
ENV VIRTUAL_HOST=backoffice.calzzapato.net
ENV LETSENCRYPT_HOST=backoffice.calzzapato.net
ENV LETSENCRYPT_EMAIL=leveltechagency@gmail.com
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build
RUN npm install -g serve
EXPOSE 5000
CMD [ "serve", "-s", "build" ]
