FROM node:12.18.3-alpine

MAINTAINER Jesús Ruiz

ENV VIRTUAL_HOST=urbanna.mx,www.urbanna.mx

ENV LETSENCRYPT_HOST=urbanna.mx,www.urbanna.mx

ENV SITEMAP_CDN=https://calzzapatodigital.s3-us-west-1.amazonaws.com/sitemaps/urbanna/sitemap.xml

ENV LETSENCRYPT_EMAIL=leveltechagency@gmail.com

ENV UUID=e2a08434-976d-44cc-b1c0-16c5235b0b62

WORKDIR /usr/app

RUN npm install --global pm2

COPY ./package*.json ./

RUN npm install --production

COPY ./ ./

RUN chmod +x ./start.sh

RUN ./start.sh

RUN npm run build

RUN rm -rf \
Makefile \
docker-compose.yml \
dockerfile-calzakids \
dockerfile-calzzapato \
dockerfile-calzzasport \
dockerfile-kelder \
dockerfile-urbanna \
home \
next.config.js \
.dockerignore \
.eslintrc.json \
.gitignore \
.git \
.gitlab-ci.yml \
src

EXPOSE 3000

USER node

CMD [ "pm2-runtime", "start", "npm", "--", "start" ]
